_BASE_: "Base-RCNN-DilatedC5.yaml"
MODEL:
  WEIGHTS: "models/VGG/VGG_ILSVRC_16_layers_v1_d2.pkl"
  PIXEL_MEAN: [103.939, 116.779, 123.68]
  BACKBONE:
    NAME: "build_mrrp_vgg_backbone"
    FREEZE_AT: 5
  MRRP:
    MRRP_ON: True
    NUM_BRANCH: 3
    BRANCH_DILATIONS: [1, 2, 4]
    TEST_BRANCH_IDX: -1
    MRRP_STAGE: "plain5"
  VGG:
    DEPTH: 16
    CONV5_DILATION: 2
  PROPOSAL_GENERATOR:
    NAME: "RPNWSL"
    MIN_SIZE: 40
  RPN:
    IN_FEATURES: ["plain5"]
    PRE_NMS_TOPK_TRAIN: 4096
    PRE_NMS_TOPK_TEST: 4096
    POST_NMS_TOPK_TRAIN: 2048
    POST_NMS_TOPK_TEST: 2048
    NMS_THRESH: 0.7
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.5
    BBOX_REG_LOSS_TYPE: "smooth_l1"
  ANCHOR_GENERATOR:
    SIZES: [[32, 64], [128, 256], [512, 768]]
    #SIZES: [[[373,326],[156,198],[116,90]],[[59,119],[62,45],[30,61]],[[33,23],[16,30],[10,13]]]
    ASPECT_RATIOS: [[1.0, 2.0, 0.5]]
  ROI_HEADS:
    NAME: "UWSODROIHeads"
    IN_FEATURES: ["plain5"]
    NUM_CLASSES: 80
    SCORE_THRESH_TEST: 0.00001
    NMS_THRESH_TEST: 0.3
    #IOU_THRESHOLDS: [0.1, 0.5]
    #IOU_LABELS: [-1, 0, 1]
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROILoopPool"
    NUM_CONV: 0
    NUM_FC: 2
    DAN_DIM: [4096, 4096]
    BBOX_REG_LOSS_TYPE: "smooth_l1"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 688
  MAX_SIZE_TEST: 4000
  CROP:
    ENABLED: True
SOLVER:
  STEPS: (140000, 200000)
  MAX_ITER: 200000  # 6.77966 epochs
  REFERENCE_WORLD_SIZE: 4
  WARMUP_ITERS: 0
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  BIAS_LR_FACTOR: 2.0
  WEIGHT_DECAY_BIAS: 0.0
TEST:
  AUG:
    ENABLED: True
    MIN_SIZES: (480, 576, 672, 768, 864, 960, 1056, 1152)
    MAX_SIZE: 4000
    FLIP: True
  EVAL_PERIOD: 10000
WSL:
  ITER_SIZE: 1
  MEAN_LOSS: True
  REFINE_NUM: 4
  REFINE_REG: [True, True, True, True]
  REFINE_MIST: True
  SAMPLING:
    SAMPLING_ON: True
    IOU_THRESHOLDS: [[0.35], [0.4], [0.45], [0.5]]
    IOU_LABELS: [[0, 1], [0, 1], [0, 1], [0, 1]]
    BATCH_SIZE_PER_IMAGE: [4096, 4096, 4096, 4096]
    POSITIVE_FRACTION: [1.0, 1.0, 1.0, 1.0]
  #VIS_TEST: True
VIS_PERIOD: 256
DATASETS:
  PROPOSAL_FILES_TRAIN: ()
  PROPOSAL_FILES_TEST: ()
